_BASE_: "../Base-ElasticDet-ResNet-RetinaNet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  BiFPN:
    OUT_CHANNELS: 160
    NUM_REPEATS: 6
SOLVER:
  IMS_PER_BATCH: 8
  MAX_ITER: 180000
  STEPS: (120000, 160000)
OUTPUT_DIR: output/ElasticDet-ResNet/R50/MS_R_50_BIFPND3_RetinaNet_1x