_BASE_: "../Base-ElasticDet-ResNet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  BiFPN:
    OUT_CHANNELS: 64
    NUM_REPEATS: 3
SOLVER:
  IMS_PER_BATCH: 32
  MAX_ITER: 45000
  STEPS: (30000, 40000)
OUTPUT_DIR: output/ElasticDet-ResNet/R50/MS_R_50_BIFPND0_FCOS_1x