MODEL:
  META_ARCHITECTURE: "OneStageDetector"
  WEIGHTS: "EN-B0-d2.pth"
  #WEIGHTS: https://isl-pretrained-models.s3.amazonaws.com/EfficientNet/EfficientNet-B0.pth
  PIXEL_MEAN: [103.53, 116.28, 123.675]
  PIXEL_STD: [57.375, 57.12 , 58.395]
  BACKBONE:
    NAME: "build_fcos_effnet_bifpn_backbone"
    FREEZE_AT: 8
  #RESNETS:
  #  OUT_FEATURES: ["res3", "res4", "res5"]
  #FPN:
  #  IN_FEATURES: ["res3", "res4", "res5"]
  EN:
    STEM_W: 32
    STRIDES: [1, 2, 2, 2, 1, 2, 1]
    DEPTHS: [1, 2, 2, 3, 3, 4, 1]
    WIDTHS: [16, 24, 40, 80, 112, 192, 320]
    EXP_RATIOS: [1, 6, 6, 6, 6, 6, 6]
    KERNELS: [3, 3, 5, 3, 5, 5, 3]
    HEAD_W: 1280
    ACTIVATION_FUN: silu
    #OUT_FEATURES: ['s3','s4','s5','s6','s7']
    OUT_FEATURES: ['s3','s4','s5','s6','s7']
    #OUT_FEATURE_STRIDES: [4, 8, 8, 16, 16]
    OUT_FEATURE_STRIDES: [2, 4, 8, 16]
    #OUT_FEATURE_CHANNELS: {"s3": 48, "s4": 96, "s5": 136, "s6": 232, "s7": 384}
    OUT_FEATURE_CHANNELS: [24, 40, 80, 112, 192, 320]
    WEIGHTS: ""
    FREEZE_AT: 1
    FROZEN_BN: 0
  BiFPN:
    IN_FEATURES: ['s3','s4','s5','s6','s7']
    OUT_CHANNELS: 64
    NUM_REPEATS: 3
    NORM: "BN"
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  FCOS:
    TOP_LEVELS: 0
    #default [8, 16, 32, 64, 128]
    #FPN_STRIDES: [2, 4, 8, 16]
    NUM_CLS_CONVS: 3
    NUM_BOX_CONVS: 3

  # PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 64
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  #STEPS: (60000, 80000)
  #MAX_ITER: 90000
  STEPS: (15000, 20000)
  MAX_ITER: 22500
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  #IMS_PER_BATCH: 16
  WEIGHT_DECAY: 4e-5


INPUT:
  #MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MIN_SIZE_TRAIN: (512,)
  #MIN_SIZE_TEST: (896,)
OUTPUT_DIR: output/EN-B0-FCOS-AGAIN



##from pycls
#MODEL:
#  TYPE: effnet
#  NUM_CLASSES: 1000
#  ACTIVATION_FUN: silu
#EN:
#  STEM_W: 40
#  STRIDES: [1, 2, 2, 2, 1, 2, 1]
#  DEPTHS: [2, 3, 3, 5, 5, 6, 2]
#  WIDTHS: [24, 32, 48, 96, 136, 232, 384]
#  EXP_RATIOS: [1, 6, 6, 6, 6, 6, 6]
#  KERNELS: [3, 3, 5, 3, 5, 5, 3]
#  HEAD_W: 1536
#OPTIM:
#  LR_POLICY: cos
#  BASE_LR: 0.4
#  MAX_EPOCH: 100
#  MOMENTUM: 0.9
#  WEIGHT_DECAY: 1e-5
#TRAIN:
#  DATASET: imagenet
#  IM_SIZE: 300
#  BATCH_SIZE: 256
#TEST:
#  DATASET: imagenet
#  IM_SIZE: 342
#  BATCH_SIZE: 200
#NUM_GPUS: 8
#OUT_DIR: .