MODEL:
  META_ARCHITECTURE: "OneStageDetector"
  WEIGHTS: ""
  BACKBONE:
    NAME: "build_fcos_effnet_bifpn_backbone"
    FREEZE_AT: 8
  #RESNETS:
  #  OUT_FEATURES: ["res3", "res4", "res5"]
  #FPN:
  #  IN_FEATURES: ["res3", "res4", "res5"]
  EN:
    STEM_W: 40
    STRIDES: [1, 2, 2, 2, 1, 2, 1]
    DEPTHS: [2, 3, 3, 5, 5, 6, 2]
    WIDTHS: [24, 32, 48, 96, 136, 232, 384]
    EXP_RATIOS: [1, 6, 6, 6, 6, 6, 6]
    KERNELS: [3, 3, 5, 3, 5, 5, 3]
    HEAD_W: 
    ACTIVATION_FUN: silu
    OUT_FEATURES: ['s3','s4','s5','s6','s7']
    WEIGHTS: "EN-B3.pth"
  BiFPN:
    IN_FEATURES: ['s3','s4','s5','s6','s7']
    OUT_CHANNELS: 160
    NORM: "BN"
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  FCOS:
    TOP_LEVELS: 0
  # PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  #MIN_SIZE_TRAIN: (896,)
  #MIN_SIZE_TEST: (896,)
OUTPUT_DIR: output/EN-B3-FCOS-2



##from pycls
#MODEL:
#  TYPE: effnet
#  NUM_CLASSES: 1000
#  ACTIVATION_FUN: silu
#EN:
#  STEM_W: 40
#  STRIDES: [1, 2, 2, 2, 1, 2, 1]
#  DEPTHS: [2, 3, 3, 5, 5, 6, 2]
#  WIDTHS: [24, 32, 48, 96, 136, 232, 384]
#  EXP_RATIOS: [1, 6, 6, 6, 6, 6, 6]
#  KERNELS: [3, 3, 5, 3, 5, 5, 3]
#  HEAD_W: 1536
#OPTIM:
#  LR_POLICY: cos
#  BASE_LR: 0.4
#  MAX_EPOCH: 100
#  MOMENTUM: 0.9
#  WEIGHT_DECAY: 1e-5
#TRAIN:
#  DATASET: imagenet
#  IM_SIZE: 300
#  BATCH_SIZE: 256
#TEST:
#  DATASET: imagenet
#  IM_SIZE: 342
#  BATCH_SIZE: 200
#NUM_GPUS: 8
#OUT_DIR: .