MODEL:
  META_ARCHITECTURE: "OneStageDetector"
  BACKBONE:
    NAME: "build_fcos_resnet_bifpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
    DEPTH: 50
    NORM: "FrozenBN"
  BiFPN:
    IN_FEATURES: ["res3", "res4", "res5"]
    OUT_CHANNELS: 160
    NUM_REPEATS: 6
    NORM: "SyncBN"
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  FCOS:
    TOP_LEVELS: 2
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  BASE_LR: 0.01
  MAX_ITER: 90000
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  STEPS: (60000, 80000)
  IMS_PER_BATCH: 32
  WEIGHT_DECAY: 4e-5
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
