_BASE_: "../Base-ElasticDet-ResNet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-152.pkl"
  RESNETS:
    DEPTH: 152
  BiFPN:
    OUT_CHANNELS: 160
    NUM_REPEATS: 6
SOLVER:
  IMS_PER_BATCH: 8
OUTPUT_DIR: output/ElasticDet-ResNet/R152/MS_R_152_BIFPND3_FCOS_1x