_BASE_: "Base-ElasticDet.yaml"
MODEL:
  WEIGHTS: https://isl-pretrained-models.s3.amazonaws.com/EfficientNet/EfficientNet-B0.pth
  EFFNET:
    STEM_W: 32
    STRIDES: [1, 2, 2, 2, 1, 2, 1]
    DEPTHS: [1, 2, 2, 3, 3, 4, 1]
    WIDTHS: [16, 24, 40, 80, 112, 192, 320]
    EXP_RATIOS: [1, 6, 6, 6, 6, 6, 6]
    KERNELS: [3, 3, 5, 3, 5, 5, 3]
    HEAD_W: 1280
  BiFPN:
    IN_FEATURES: ["s3","s4","s5","s6","s7"]
    OUT_CHANNELS: 64
    NUM_REPEATS: 3
INPUT:
  MIN_SIZE_TRAIN: (512,)
OUTPUT_DIR: output/ElasticDet/D0_1x/
