_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  BACKBONE:
    NAME: "build_retinanet_effnet_bifpn_backbone"
  EFFNET:
    OUT_FEATURES: ["s3","s4","s5","s6","s7"]
    NORM: "SyncBN"
    ACTIVATION_FUN: "silu"
    STEM_W: 32
    STRIDES: [1, 2, 2, 2, 1, 2, 1]
    DEPTHS: [1, 2, 2, 3, 3, 4, 1]
    WIDTHS: [16, 24, 40, 80, 112, 192, 320]
    EXP_RATIOS: [1, 6, 6, 6, 6, 6, 6]
    KERNELS: [3, 3, 5, 3, 5, 5, 3]
    HEAD_W: 1280
  BiFPN:
    IN_FEATURES: ["s3","s4","s5","s6","s7"]
    NORM: "SyncBN"
SOLVER:
  BASE_LR: 0.01
  MAX_ITER: 90000
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  IMS_PER_BATCH: 16
  WEIGHT_DECAY: 4e-5