_BASE_: "Base-EfficientDet.yaml"
MODEL:
  WEIGHTS: https://isl-pretrained-models.s3.amazonaws.com/EfficientNet/EfficientNet-B5.pth
  EFFNET:
    STEM_W: 48
    STRIDES: [1, 2, 2, 2, 1, 2, 1]
    DEPTHS: [3, 5, 5, 7, 7, 9, 3]
    WIDTHS: [24, 40, 64, 128, 176, 304, 512]
    EXP_RATIOS: [1, 6, 6, 6, 6, 6, 6]
    KERNELS: [3, 3, 5, 3, 5, 5, 3]
    HEAD_W: 2048
  BiFPN:
    IN_FEATURES: ["s3","s4","s5","s6","s7"]
    OUT_CHANNELS: 288
    NUM_REPEATS: 7
INPUT:
  MIN_SIZE_TRAIN: (512,)
OUTPUT_DIR: output/EfficientDet/D5_1x/
