_BASE_: "Base-EfficientDet.yaml"
MODEL:
  WEIGHTS: https://dl.fbaipublicfiles.com/pycls/dds_baselines/161305613/EN-B0_dds_8gpu.pyth
  EFFNET:
    STRIDES: [1, 2, 2, 2, 1, 2, 1]
    DEPTHS: [1, 2, 2, 3, 3, 4, 1]
    WIDTHS: [16, 24, 40, 80, 112, 192, 320]
    EXP_RATIOS: [1, 6, 6, 6, 6, 6, 6]
    KERNELS: [3, 3, 5, 3, 5, 5, 3]
  BiFPN:
    IN_FEATURES: ["s3","s4","s5","s6","s7"]
    OUT_CHANNELS: 64
    NUM_REPEATS: 3
    NORM: "BN"
INPUT:
  MIN_SIZE_TRAIN: (512,)
OUTPUT_DIR: output/Efficient/D0/