_BASE_: "Base-EfficientDet.yaml"
MODEL:
  WEIGHTS: https://isl-pretrained-models.s3.amazonaws.com/EfficientNet/EfficientNet-B4.pth
  EFFNET:
    STEM_W: 48
    STRIDES: [1, 2, 2, 2, 1, 2, 1]
    DEPTHS: [2, 4, 4, 6, 6, 8, 2]
    WIDTHS: [24, 32, 56, 112, 160, 272, 448]
    EXP_RATIOS: [1, 6, 6, 6, 6, 6, 6]
    KERNELS: [3, 3, 5, 3, 5, 5, 3]
    HEAD_W: 1792
  BiFPN:
    IN_FEATURES: ["s3","s4","s5","s6","s7"]
    OUT_CHANNELS: 224
    NUM_REPEATS: 7
INPUT:
  MIN_SIZE_TRAIN: (512,)
OUTPUT_DIR: output/Efficient/D4/
