MODEL:
  META_ARCHITECTURE: "ProposalNetwork"
  BACKBONE:
    NAME: "build_effnet_fpn_backbone"
  EffNet:
    STEM_W: 32
    STRIDES: [1, 2, 2, 2, 1, 2, 1]
    DEPTHS: [1, 2, 2, 3, 3, 4, 1]
    WIDTHS: [16, 24, 40, 80, 112, 192, 320]
    EXP_RATIOS: [1, 6, 6, 6, 6, 6, 6]
    KERNELS: [3, 3, 5, 3, 5, 5, 3]
    HEAD_W: 1280
    MODEL_ACTIVATION_FUN: silu
    OUT_FEATURES: ["s3", "s4", "s5", "s6", "s7"]
    # OUT_FEATURE_STRIDES: {"s3": 4, "s4": 8, "s5": 8, "s6": 16, "s7": 16}
    # OUT_FEATURE_STRIDES: [4, 8, 8, 16, 16]
    # OUT_FEATURE_STRIDES: {"s3": 4, "s4": 8, "s5": 16, "s6": 32, "s7": 64}
    # OUT_FEATURE_CHANNELS: {"s3": 48, "s4": 96, "s5": 136, "s6": 232, "s7": 384}
    # OUT_FEATURE_CHANNELS: [40, 80, 112, 192, 320]
  FPN:
    IN_FEATURES: ["s3", "s4", "s5", "s6", "s7"]
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p3", "p4", "p5", "p6", "p7"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p3", "p4", "p5", "p6", "p7"]
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
